### ISSUE TITLE
Power Level / Torque / etc

### ISSUE THREAD

**Issue by ghost** [MarkTillotson/DRV8711#1]
Good day

Thank you for a really awesome library, I got my boost pack spinning using your library off an Arduino quicker than I could download Code Composer studio (so that was a $9.99 waste lol)

Anyway, my use for your library will be primarilly to init the DRV8711, I tried figuring it out by looking at the .h and .cpp files but I must admit I am a little clueless.

Let me elaborate.

I'd create my object as DRV8711 xmotor(CSpin) ;  (final version will have 4 devices on the SPI bus, thus each with their own CS pin.  Easy enough

Next I need to init the driver, now using your example I got it spinning in no time at all:

xmotor.begin (60, 8, 2, 0, 1, 0) ;

From the .cpp I gathered:

void DRV8711::begin (byte drive, 
                     unsigned int microsteps, 
                     byte decay_mode,
                     byte gate_speed, 
                     byte gate_drive,
                     byte deadtime)

Can you elaborate on what I need to make said values ?  

I played with the 2nd byte for example, setting it to 16 and 4 in turn.  In 4 the motor stalls (so my step rate is probably too high for 1/4 step, in 16 it seems to run slower (more steps per rotation as expected), so it looks like thats easy enough, should be 16 for 1/16th microstep, and maybe 256 for 1/256 microsteps?

Decay mode

I see in the .h: 
# define DRV8711DEC_SLOW_DECAY     0x000
# define DRV8711DEC_SLOW_MIXED     0x100
# define DRV8711DEC_FAST_DECAY     0x200
# define DRV8711DEC_MIXED_DECAY    0x300
# define DRV8711DEC_SLOW_AUTOMIX   0x400
# define DRV8711DEC_AUTOMIX        0x500

So in your example 

xmotor. stepper.begin (60, 8, 2, 0, 1, 0) ;

the 3rd byte is 2,   is that read as from the table in drv8711.h that 2 = FAST DECAY?   And thus if I want Automix instead for example I set the 3rd byte to 5?

The default dead time, gate drive and gate speed should stay the same since I am using the same mosfets as the boost pack....

So my last question is the first byte:  DRIVE - set to 60 in your example.    Is that 60% torque? I.e. 60% of the 5A setting? 

Sorry about the stupididy of the questions.   I will update the example sketch with comments and submit a pull request once I figured it out a little better with your answers' help.

**Comment by openhardwarecoza** [comment]
Oops sorry clicked "comment" by accident before I was done...

xmotor..begin (60, 8, 2, 0, 1, 0) ;

From the .cpp I gathered:

void DRV8711::begin (byte drive, 
                     unsigned int microsteps, 
                     byte decay_mode,
                     byte gate_speed, 
                     byte gate_drive,
                     byte deadtime)


Can you elaborate on what I need to make said values ?  

I played with the 2nd byte for example, setting it to 16 and 4 in turn.  In 4 the motor stalls (so my step rate is probably too high for 1/4 step, in 16 it seems to run slower (more steps per rotation as expected), so it looks like thats easy enough, should be 16 for 1/16th microstep, and maybe 256 for 1/256 microsteps?

Decay mode

I see in the .h: 
#define DRV8711DEC_SLOW_DECAY     0x000
#define DRV8711DEC_SLOW_MIXED     0x100
#define DRV8711DEC_FAST_DECAY     0x200
#define DRV8711DEC_MIXED_DECAY    0x300
#define DRV8711DEC_SLOW_AUTOMIX   0x400
#define DRV8711DEC_AUTOMIX        0x500


So in your example 

xmotor. stepper.begin (60, 8, 2, 0, 1, 0) ;

the 3rd byte is 2,   is that read as from the table in drv8711.h that 2 = FAST DECAY?   And thus if I want Automix instead for example I set the 3rd byte to 5?


The default dead time, gate drive and gate speed should stay the same since I am using the same mosfets as the boost pack....

So my last question is the first byte:  DRIVE - set to 60 in your example.    Is that 60% torque? I.e. 60% of the 5A setting? 

Sorry about the stupididy of the questions.   I will update the example sketch with comments and submit a pull request once I figured it out a little better with your answers' help.

**Comment by ghost** [comment]
Okay so I have played around some more, and answered one of my own questions...

I did test Microstepping with values as 8, 16, 32... all the way to 256 - great, working a treat!  Confims my question above: "so it looks like thats easy enough, should be 16 for 1/16th microstep, and maybe 256 for 1/256 microsteps?" to be true...

Torque is still my major question though

If I look through the datasheet I understand from 

If a 0.1-Ω sense resistor is used, ISGAIN is set to 0 (gain of 5), and TORQUE is set to 255, the full-scale (100%)   chopping current will be (2.75 V \* 255) / (256 \* 5 \* 0.1 Ω) = 5.5 A

In the case of the Boost packs we have 0.05 Ω so to get 5.5A drive (Max rated) the ISGain should never be set to 5.  It should be set to 10.

The Torque bit in this example is set to 255 (full scale).   

This is the part of your library I can't figure out... How do I set Torque between 1 and 255?

**Comment by ghost** [comment]
I see you were still active on the Propellor forums over the weekend so I know at least you are still alive (:

I started populating your Wiki:  https://github.com/MarkTillotson/DRV8711/wiki

I found stepper.power()?  Is that what I was looking for?

**Comment by ghost** [comment]
stepper.power(DRV8711_FULL); and stepper.power(DRV8711_HALF); ?

**Comment by MarkTillotson** [comment]
Sorry, v. busy ATM.

Torque: You've got the code, I can't remember, I'd just have to look at it too!

The FULL and HALF values select full and half power respectively - its all in the code.

The code _is_ the documentation, adding a Wiki in my github **without my approval** means
either I have to check it for accuracy and spend time on it (that I do not have ATM), or I'll simply delete it.

**Comment by MarkTillotson** [comment]
If you can't read code, please don't document it with guesswork, that just lowers the quality
of the information that was there already.

**Comment by ghost** [comment]
(: Thanks dude, was just trying to help as I realised by the 4 day delay you must be busy - but nevermind, will take my help elsewhere (:

Documenting your project would have made it more useful to everyone, but oh well. Just delete the Repo if thats how you roll (;
